# Generated by Django 5.2.4 on 2025-07-26 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the RSS feed', max_length=200)),
                ('url', models.URLField(help_text='RSS feed URL', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the podcast feed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to actively process this feed')),
                ('last_processed', models.DateTimeField(blank=True, help_text='Last time this feed was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='podcast',
            name='rss_feed',
            field=models.ForeignKey(blank=True, help_text='RSS feed this podcast came from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='audio_processing.rssfeed'),
        ),
    ]
