# Generated by Django 5.2.4 on 2025-07-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0002_rssfeed_podcast_rss_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='name',
            field=models.CharField(help_text='Friendly name for the RSS feed', max_length=1000),
        ),
    ]
