# Generated by Django 5.2.4 on 2025-07-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0003_alter_rssfeed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='raw_audio_url',
            field=models.URLField(help_text='URL of the raw audio file', max_length=2000),
        ),
    ]
