# Generated by Django 5.2.4 on 2025-07-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0004_alter_podcast_raw_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly tag name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the tag', null=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code for the tag (e.g., #FF5733)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this podcast', related_name='podcasts', to='audio_processing.tag'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this RSS feed', related_name='rss_feeds', to='audio_processing.tag'),
        ),
    ]
