# Generated by Django 5.2.4 on 2025-07-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0005_tag_podcast_tags_rssfeed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='script_transcript',
            field=models.TextField(blank=True, help_text='Formatted transcript with speaker identification', null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='transcript',
            field=models.TextField(blank=True, help_text='Raw transcript from speech-to-text', null=True),
        ),
    ]
