# Generated by Django 5.2.4 on 2025-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0006_podcast_script_transcript_alter_podcast_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the episode', null=True),
        ),
    ]
