# Generated by Django 5.2.4 on 2025-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0007_podcast_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Original release date of the podcast episode', null=True),
        ),
    ]
