# Generated by Django 5.2.4 on 2025-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processing', '0008_podcast_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the podcast episode', max_length=512, null=True),
        ),
    ]
